INSERT INTO styles VALUES({0}, 'anyBackgroundVal', 'White');
INSERT INTO styles VALUES({0}, 'anyForegroundVal', 'Black');
INSERT INTO styles VALUES({0}, 'anyBorderBrushVal', 'Black');
INSERT INTO styles VALUES({0}, 'anyFontFamilyVal', 'Segoe UI');
INSERT INTO styles VALUES({0}, 'anyFontSizeVal', '12');
INSERT INTO styles VALUES({0}, 'anyFontStyleVal', 'Normal');
INSERT INTO styles VALUES({0}, 'anyFontWeightVal', 'Normal');
INSERT INTO styles VALUES({0}, 'anyTBBackgroundVal', 'White');
INSERT INTO styles VALUES({0}, 'anyTBForegroundVal', 'Black');
INSERT INTO styles VALUES({0}, 'anyTBBorderBrushVal', 'Black');
INSERT INTO styles VALUES({0}, 'anyTBSelectionBrushVal', '#FF0078D7');
INSERT INTO styles VALUES({0}, 'anyTBCaretBrushVal', 'Black');
INSERT INTO styles VALUES({0}, 'anyTBCornerVal', '0');
INSERT INTO styles VALUES({0}, 'anyTBFontFamilyVal', 'Segoe UI');
INSERT INTO styles VALUES({0}, 'anyTBFontSizeVal', '12');
INSERT INTO styles VALUES({0}, 'anyTBFontStyleVal', 'Normal');
INSERT INTO styles VALUES({0}, 'anyTBFontWeightVal', 'Normal');
INSERT INTO styles VALUES({0}, 'anyButtonBackgroundVal', '#FFDDDDDD');
INSERT INTO styles VALUES({0}, 'anyButtonForegroundVal', 'Black');
INSERT INTO styles VALUES({0}, 'anyButtonBorderBrushVal', 'Black');
INSERT INTO styles VALUES({0}, 'anyButtonMouseOverVal', 'White');
INSERT INTO styles VALUES({0}, 'anyButtonPressedVal', 'Blue');
INSERT INTO styles VALUES({0}, 'anyButtonCornerVal', '0');
INSERT INTO styles VALUES({0}, 'anyButtonFontFamilyVal', 'Segoe UI');
INSERT INTO styles VALUES({0}, 'anyButtonFontSizeVal', '12');
INSERT INTO styles VALUES({0}, 'anyButtonFontStyleVal', 'Normal');
INSERT INTO styles VALUES({0}, 'anyButtonFontWeightVal', 'Normal');
INSERT INTO styles VALUES({0}, 'anyTabItemBackgroundVal', 'White');
INSERT INTO styles VALUES({0}, 'anyTabItemForegroundVal', 'Black');
INSERT INTO styles VALUES({0}, 'anyTabItemBorderBrushVal', 'Black');
INSERT INTO styles VALUES({0}, 'anyTabItemCornerVal', '0');
INSERT INTO styles VALUES({0}, 'anyTabItemFontFamilyVal', 'Segoe UI');
INSERT INTO styles VALUES({0}, 'anyTabItemFontSizeVal', '12');
INSERT INTO styles VALUES({0}, 'anyTabItemFontStyleVal', 'Normal');
INSERT INTO styles VALUES({0}, 'anyTabItemFontWeightVal', 'Normal');
INSERT INTO styles VALUES({0}, 'anyComboBackgroundVal', 'White');
INSERT INTO styles VALUES({0}, 'anyComboForegroundVal', 'Black');
INSERT INTO styles VALUES({0}, 'anyComboBorderBrushVal', 'Black');
INSERT INTO styles VALUES({0}, 'anyComboArrowVal', 'Orange');
INSERT INTO styles VALUES({0}, 'anyComboMouseOverVal', 'White');
INSERT INTO styles VALUES({0}, 'anyComboPressedVal', 'Blue');
INSERT INTO styles VALUES({0}, 'anyComboUnpressedVal', 'Red');
INSERT INTO styles VALUES({0}, 'anyComboPopupBackVal', 'White');
INSERT INTO styles VALUES({0}, 'anyComboPopupBorderVal', 'Blue');
INSERT INTO styles VALUES({0}, 'anyComboCornerVal', '5');
INSERT INTO styles VALUES({0}, 'anyComboCornerArrowVal', '5,0,0,5');
INSERT INTO styles VALUES({0}, 'anyComboFontFamilyVal', 'Segoe UI');
INSERT INTO styles VALUES({0}, 'anyComboFontSizeVal', '12');
INSERT INTO styles VALUES({0}, 'anyComboFontStyleVal', 'Normal');
INSERT INTO styles VALUES({0}, 'anyComboFontWeightVal', 'Normal');